// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 6.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'flutter_project';

  static const String assets_images_location_png = 'assets/images/location.png';
  static const String flutter_project$assets_images_location_png = 'packages/flutter_project/assets/images/location.png';

  static const String assets_styles_bold_txt = 'assets/styles/bold.txt';
  static const String flutter_project$assets_styles_bold_txt = 'packages/flutter_project/assets/styles/bold.txt';

  static const String assets_styles_elegent_txt = 'assets/styles/elegent.txt';
  static const String flutter_project$assets_styles_elegent_txt = 'packages/flutter_project/assets/styles/elegent.txt';

  static const String assets_styles_nighttime_txt = 'assets/styles/nighttime.txt';
  static const String flutter_project$assets_styles_nighttime_txt = 'packages/flutter_project/assets/styles/nighttime.txt';

  static const String assets_styles_pastel_txt = 'assets/styles/pastel.txt';
  static const String flutter_project$assets_styles_pastel_txt = 'packages/flutter_project/assets/styles/pastel.txt';

  static const String assets_styles_vibrant_txt = 'assets/styles/vibrant.txt';
  static const String flutter_project$assets_styles_vibrant_txt = 'packages/flutter_project/assets/styles/vibrant.txt';
}
