// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'flutter_project';

  static const String assets_images_location_png = 'assets/images/location.png';
  static const String flutter_project$assets_images_location_png = 'packages/flutter_project/assets/images/location.png';
}
